### ISSUE TITLE
Add functionality to select custom interval for refreshing pages

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/chrome-tab-reloader#3]
- The functionality is currently limited to reload the page after 10 seconds as fixed interval.
- This should be customizable.
- This issue is almost Hello World of chrome extensions and will be a great hands on experience.

**Comment by derekdkim** [comment]
May I give this a shot? I don't have any experience with Chrome extensions and this looks like a great opportunity to learn about it.

**Comment by sushrut111** [comment]
Sure. Go ahead and start working on it! @derekdkim

**Comment by KeshriAyushi22** [comment]
I too wanted to give a try on this . Please assign this to me aswell @sushrut111

**Comment by sushrut111** [comment]
Hi @KeshriAyushi22 , if you are interested to work on this particular enhancement, please feel free to start working on it. If you just want to work on a chrome extension and are okay to try out a different issue, please take a look at #6 , that is a good starter too! Please confirm on the particular issue which you want to be assigned to! Thank you for your interest in contributing to this repository.
