### ISSUE TITLE
Fix errors when the tab registered for auto reload is removed

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/chrome-tab-reloader#6]
## Issue:
- When a tab registered for auto reload is closed, the entry related to it in the local storage of chrome becomes orphaned but the reload hook keeps trying to reload the tab with the registered tab id.
![Screenshot 2020-10-07 at 11 35 30 AM](https://user-images.githubusercontent.com/11269256/95293799-c39c1b80-0891-11eb-8330-8575d1ea7bb9.png)

## How to reproduce:
1. Install the extension following the instructions from the README.md
2. Open a new tab.
3. Click on the extension icon to enable it and check the `Activate Timer` checkbox.
4. Head to [chrome://extensions](chrome://extensions) and click on `inspect views: background page`
![Screenshot 2020-10-07 at 11 46 27 AM](https://user-images.githubusercontent.com/11269256/95294585-2c37c800-0893-11eb-9902-478763ef2904.png)
5. Close the tab where you have enabled the auto reload.

**Comment by KeshriAyushi22** [comment]
I wanted to create a extension in react but failed, this might give me some closure .i will look around , you can assign me this one instead

**Comment by sushrut111** [comment]
I have assigned this to you.

**Comment by KeshriAyushi22** [comment]
@sushrut111 i tried changing but how can i live debug it, that extension i need to re-deploy? i wanted to have look on some values can u help me plz

**Comment by sushrut111** [comment]
Sure, let me know what help you need!
To debug the live extension, first uninstall the extension if you installed one from Chrome Store.
Then install the one from the repository following the instructions in readme. You can ping me here with the issue you are facing and I will be able to help you.

**Comment by sushrut111** [comment]
You do not have to re-install extension, you just have to click the reload icon in the extension's window (one beside the Errors button in this snippet)

![](https://user-images.githubusercontent.com/11269256/95294585-2c37c800-0893-11eb-9902-478763ef2904.png)

**Comment by sushrut111** [comment]
@KeshriAyushi22 You do not have reinstall the extension after every change. You can click the reload button (one beside the Errors button in the snippet below)

![](https://user-images.githubusercontent.com/11269256/95294585-2c37c800-0893-11eb-9902-478763ef2904.png)

**Comment by KeshriAyushi22** [comment]
Hi,
the refresh btn is not here any other way
[image: image.png]
*Thanks and Regards*
*Ayushi  Keshri*

**Comment by sushrut111** [comment]
@KeshriAyushi22 Looks like the image has not been attached properly.
Did you enable developer mode?
Did you install extension from file?

**Comment by KeshriAyushi22** [comment]
Yes I did.. unpacked it and then inspect the background page

**Comment by KeshriAyushi22** [comment]
Okay yeah got it now. Thanks.

**Comment by sushrut111** [comment]
That's great!

**Comment by KeshriAyushi22** [comment]
![image](https://user-images.githubusercontent.com/49064703/95483033-621c9f80-09ac-11eb-9355-d78400aad8ff.png)
hey, I just consoled this message when the tab exists . Is this you want

**Comment by sushrut111** [comment]
Yes that one. You have to handle the case of deletion of tab and remove the
entry related to it.

**Comment by KeshriAyushi22** [comment]
yes, I just created a pull request you can check, i deleted the entry so
its not calling it infinite times.
*Thanks and Regards*
*Ayushi  Keshri*
